# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HolisticJourney' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HolisticJourney

pod 'Firebase/Core'
pod 'Fabric', '~> 1.7.11'
pod 'Crashlytics', '~> 3.10.7'

  target 'HolisticJourney-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HolisticJourneyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HolisticJourney-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HolisticJourney-tvOS

end
